default_language_version:
    python: python3
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the ref you want to point at
    hooks:
      - id: check-merge-conflict
      - id: debug-statements

-   repo: https://github.com/psf/black
    rev: "22.10.0"
    hooks:
      - id: black

-   repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ['--show-source', '--statistics']
        exclude: scrapers/il/tests/
