version: "3"
services:
  openstates:
    build: .
    environment:
    - BILLY_MONGO_HOST=database
    - MYSQL_HOST=mysql
    - NEW_YORK_API_KEY
    - INDIANA_API_KEY
    volumes:
    - .:/srv/openstates-web
    ports:
    - "8000:8000"
    depends_on:
    - database
  database:
    image: mongo
    ports:
    - "27017:27017"
  mysql:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_DATABASE=capublic
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
