version: "2"
services:
  scrape:
    build: .
    environment:
    - BILLY_MONGO_HOST=database
    - NEW_YORK_API_KEY
    - INDIANA_API_KEY
    volumes:
    - .:/opt/openstates/openstates/
    depends_on:
    - database
    entrypoint: /opt/openstates/openstates/scrape.sh
  database:
    image: mongo
    ports:
    - "27017:27017"
